### ISSUE TITLE
opam install otoggl doesnt work

### ISSUE THREAD

**Issue by idkjs** [unitrack-time-tracking/OToggl#1]
Looks like its not on opam.

**Comment by christophe-riolo** [comment]
Hello ! Indeed, I had not touched this project after we changed our work time logging at work, by lack of time, but if you or anyone else is interested I can resume the integration and publish on Opam! There would be some work to do as Toggl updated their API, or at least the URLs, so I wouldn't publish immediately, it requires some work

**Comment by christophe-riolo** [comment]
Hello, now the current bindings have been released to opam ! I see that the packaging could be better (you need to `#require "otoggl.lib"` instead of just `#require "otoggl"` but I will still mark this issue as done, and make a new issue for that
